name: 'IntelliJ Inspections'
description: 'Runs IntelliJ Inspections on a PR'
author: 'Gopal Sharma <gps@surya-soft.com>'
inputs:
  GH_TOKEN:
    description: GitHub Token used to comment on PR
    required: True
  INSPECTIONS_FILE:
    description: Path to inspections file relative to root of project directory
    required: True
  IGNORE_FILE_PATTERNS:
    description: Regular expressions for the files to be ignored. The inputs are specified within square brackets where each input regular expression is enclosed within double quotes, comma separated and with correct indentations.
    required: False
runs:
  using: 'docker'
  image: 'Dockerfile'
